package com.utahmsd.pupper.dao.entity;

import com.utahmsd.pupper.dto.PupperEntity;

import javax.persistence.*;
import javax.validation.Valid;
import javax.ws.rs.DefaultValue;
import java.io.Serializable;
import java.time.Instant;

/**
 * Entity containing MatchResult data generated by the PupperMatcherService.
 */

@Entity
@Table(name = "match_result",
        indexes = {@Index(columnList = "match_profile_id_fk_1", name = "match_result_ibfk_1"),
        @Index(columnList = "match_profile_id_fk_2", name = "match_result_ibfk_2")})
public class MatchResult extends PupperEntity implements Serializable {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", updatable = false, nullable = false)
    private Long id;

    @ManyToOne(fetch = FetchType.LAZY) //A match result corresponds to multiple (2) match profiles, and a match profile has many match results
    @JoinColumn(name = "match_profile_id_fk_1", referencedColumnName = "id")
    @Valid
    private MatchProfile matchProfileOne;

    @Column(name = "match_profile_1_result")
    @DefaultValue("null")
    private Boolean matchForProfileOne;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "match_profile_id_fk_2", referencedColumnName = "id")
    @Valid
    private MatchProfile matchProfileTwo;

    @Column(name = "match_profile_2_result")
    @DefaultValue("null")
    private Boolean matchForProfileTwo;

    @Column(name = "batch_sent")
    private Instant batchSent;

    @Column(name = "match_result_completed")
    private Instant resultCompleted;

    @Column(name ="record_expires")
    private Instant recordExpires;

    public Long getId() { return id; }

    public void setId(Long id) { this.id = id; }

    public MatchProfile getMatchProfileOne() { return matchProfileOne; }

    public void setMatchProfileOne(MatchProfile matchProfileOne) { this.matchProfileOne = matchProfileOne; }

    public Boolean isMatchForProfileOne() { return matchForProfileOne; }

    public void setMatchForProfileOne(Boolean matchForProfileOne) { this.matchForProfileOne = matchForProfileOne; }

    public MatchProfile getMatchProfileTwo() { return matchProfileTwo; }

    public void setMatchProfileTwo(MatchProfile matchProfileTwo) { this.matchProfileTwo = matchProfileTwo; }

    public Boolean isMatchForProfileTwo() { return matchForProfileTwo; }

    public void setMatchForProfileTwo(Boolean matchForProfileTwo) { this.matchForProfileTwo = matchForProfileTwo; }

    public Instant getBatchSent() { return batchSent; }

    public void setBatchSent(Instant batchSent) { this.batchSent = batchSent; }

    public Instant getResultCompleted() { return resultCompleted; }

    public void setResultCompleted(Instant resultCompleted) { this.resultCompleted = resultCompleted; }

    public Instant getRecordExpires() { return recordExpires; }

    public void setRecordExpires(Instant recordExpires) { this.recordExpires = recordExpires; }
}
